export interface SkillBadge {
  id: string;
  name: string;
  category: string;
  badgeUrl: string;
}

export const SKILL_CATEGORIES = [
  { id: 'languages', label: 'Languages' },
  { id: 'frameworks', label: 'Frameworks, Platforms & Libraries' },
  { id: 'hosting', label: 'Hosting / SaaS' },
  { id: 'servers', label: 'Servers' },
  { id: 'databases', label: 'Databases & ORM' },
  { id: 'design', label: 'Design' },
  { id: 'mldl', label: 'ML / DL' },
  { id: 'cicd', label: 'CI/CD & VCS' },
  { id: 'testing', label: 'Testing' },
  { id: 'other', label: 'Other' },
] as const;

export const SKILL_BADGES: SkillBadge[] = [
  // ── LANGUAGES ──
  { id: 'typescript', name: 'TypeScript', category: 'languages', badgeUrl: 'https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white' },
  { id: 'javascript', name: 'JavaScript', category: 'languages', badgeUrl: 'https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black' },
  { id: 'python', name: 'Python', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=python&logoColor=white' },
  { id: 'rust', name: 'Rust', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Rust-000000?style=for-the-badge&logo=rust&logoColor=white' },
  { id: 'go', name: 'Go', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Go-00ADD8?style=for-the-badge&logo=go&logoColor=white' },
  { id: 'cpp', name: 'C++', category: 'languages', badgeUrl: 'https://img.shields.io/badge/C%2B%2B-00599C?style=for-the-badge&logo=c%2B%2B&logoColor=white' },
  { id: 'c', name: 'C', category: 'languages', badgeUrl: 'https://img.shields.io/badge/C-00599C?style=for-the-badge&logo=c&logoColor=white' },
  { id: 'csharp', name: 'C#', category: 'languages', badgeUrl: 'https://img.shields.io/badge/C%23-239120?style=for-the-badge&logo=csharp&logoColor=white' },
  { id: 'java', name: 'Java', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=openjdk&logoColor=white' },
  { id: 'kotlin', name: 'Kotlin', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Kotlin-7F52FF?style=for-the-badge&logo=kotlin&logoColor=white' },
  { id: 'swift', name: 'Swift', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Swift-FA7343?style=for-the-badge&logo=swift&logoColor=white' },
  { id: 'dart', name: 'Dart', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Dart-0175C2?style=for-the-badge&logo=dart&logoColor=white' },
  { id: 'ruby', name: 'Ruby', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Ruby-CC342D?style=for-the-badge&logo=ruby&logoColor=white' },
  { id: 'php', name: 'PHP', category: 'languages', badgeUrl: 'https://img.shields.io/badge/PHP-777BB4?style=for-the-badge&logo=php&logoColor=white' },
  { id: 'scala', name: 'Scala', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Scala-DC322F?style=for-the-badge&logo=scala&logoColor=white' },
  { id: 'elixir', name: 'Elixir', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Elixir-4B275F?style=for-the-badge&logo=elixir&logoColor=white' },
  { id: 'lua', name: 'Lua', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Lua-2C2D72?style=for-the-badge&logo=lua&logoColor=white' },
  { id: 'r', name: 'R', category: 'languages', badgeUrl: 'https://img.shields.io/badge/R-276DC3?style=for-the-badge&logo=r&logoColor=white' },
  { id: 'html5', name: 'HTML5', category: 'languages', badgeUrl: 'https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white' },
  { id: 'css3', name: 'CSS3', category: 'languages', badgeUrl: 'https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white' },
  { id: 'sass', name: 'Sass', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Sass-CC6699?style=for-the-badge&logo=sass&logoColor=white' },
  { id: 'shell', name: 'Shell Script', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Shell_Script-121011?style=for-the-badge&logo=gnu-bash&logoColor=white' },
  { id: 'powershell', name: 'PowerShell', category: 'languages', badgeUrl: 'https://img.shields.io/badge/PowerShell-5391FE?style=for-the-badge&logo=powershell&logoColor=white' },
  { id: 'markdown', name: 'Markdown', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Markdown-000000?style=for-the-badge&logo=markdown&logoColor=white' },
  { id: 'solidity', name: 'Solidity', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Solidity-363636?style=for-the-badge&logo=solidity&logoColor=white' },
  { id: 'haskell', name: 'Haskell', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Haskell-5D4F85?style=for-the-badge&logo=haskell&logoColor=white' },
  { id: 'zig', name: 'Zig', category: 'languages', badgeUrl: 'https://img.shields.io/badge/Zig-F7A41D?style=for-the-badge&logo=zig&logoColor=white' },

  // ── FRAMEWORKS, PLATFORMS & LIBRARIES ──
  { id: 'react', name: 'React', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB' },
  { id: 'nextjs', name: 'Next.js', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=nextdotjs&logoColor=white' },
  { id: 'vue', name: 'Vue.js', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Vue.js-35495E?style=for-the-badge&logo=vuedotjs&logoColor=4FC08D' },
  { id: 'nuxt', name: 'Nuxt.js', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Nuxt.js-00DC82?style=for-the-badge&logo=nuxtdotjs&logoColor=white' },
  { id: 'angular', name: 'Angular', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Angular-DD0031?style=for-the-badge&logo=angular&logoColor=white' },
  { id: 'svelte', name: 'Svelte', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Svelte-FF3E00?style=for-the-badge&logo=svelte&logoColor=white' },
  { id: 'tailwindcss', name: 'Tailwind CSS', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&logoColor=white' },
  { id: 'bootstrap', name: 'Bootstrap', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Bootstrap-563D7C?style=for-the-badge&logo=bootstrap&logoColor=white' },
  { id: 'nodejs', name: 'Node.js', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Node.js-43853D?style=for-the-badge&logo=node.js&logoColor=white' },
  { id: 'express', name: 'Express', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Express-000000?style=for-the-badge&logo=express&logoColor=white' },
  { id: 'django', name: 'Django', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Django-092E20?style=for-the-badge&logo=django&logoColor=white' },
  { id: 'flask', name: 'Flask', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Flask-000000?style=for-the-badge&logo=flask&logoColor=white' },
  { id: 'fastapi', name: 'FastAPI', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/FastAPI-009688?style=for-the-badge&logo=fastapi&logoColor=white' },
  { id: 'spring', name: 'Spring', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Spring-6DB33F?style=for-the-badge&logo=spring&logoColor=white' },
  { id: 'dotnet', name: '.NET', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/.NET-512BD4?style=for-the-badge&logo=dotnet&logoColor=white' },
  { id: 'rails', name: 'Rails', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Rails-CC0000?style=for-the-badge&logo=ruby-on-rails&logoColor=white' },
  { id: 'flutter', name: 'Flutter', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Flutter-02569B?style=for-the-badge&logo=flutter&logoColor=white' },
  { id: 'reactnative', name: 'React Native', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/React_Native-20232A?style=for-the-badge&logo=react&logoColor=61DAFB' },
  { id: 'electron', name: 'Electron', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Electron-2B2E3A?style=for-the-badge&logo=electron&logoColor=9FEAF9' },
  { id: 'jquery', name: 'jQuery', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/jQuery-0769AD?style=for-the-badge&logo=jquery&logoColor=white' },
  { id: 'redux', name: 'Redux', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Redux-764ABC?style=for-the-badge&logo=redux&logoColor=white' },
  { id: 'threejs', name: 'Three.js', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Three.js-000000?style=for-the-badge&logo=three.js&logoColor=white' },
  { id: 'gatsby', name: 'Gatsby', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Gatsby-663399?style=for-the-badge&logo=gatsby&logoColor=white' },
  { id: 'remix', name: 'Remix', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Remix-000000?style=for-the-badge&logo=remix&logoColor=white' },
  { id: 'astro', name: 'Astro', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Astro-FF5D01?style=for-the-badge&logo=astro&logoColor=white' },
  { id: 'bun', name: 'Bun', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Bun-000000?style=for-the-badge&logo=bun&logoColor=white' },
  { id: 'deno', name: 'Deno', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Deno-000000?style=for-the-badge&logo=deno&logoColor=white' },
  { id: 'vite', name: 'Vite', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Vite-646CFF?style=for-the-badge&logo=vite&logoColor=white' },
  { id: 'webpack', name: 'Webpack', category: 'frameworks', badgeUrl: 'https://img.shields.io/badge/Webpack-8DD6F9?style=for-the-badge&logo=webpack&logoColor=black' },

  // ── HOSTING / SaaS ──
  { id: 'aws', name: 'AWS', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/AWS-232F3E?style=for-the-badge&logo=amazon-aws&logoColor=white' },
  { id: 'gcp', name: 'Google Cloud', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Google_Cloud-4285F4?style=for-the-badge&logo=google-cloud&logoColor=white' },
  { id: 'azure', name: 'Azure', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Azure-0078D4?style=for-the-badge&logo=microsoftazure&logoColor=white' },
  { id: 'vercel', name: 'Vercel', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Vercel-000000?style=for-the-badge&logo=vercel&logoColor=white' },
  { id: 'netlify', name: 'Netlify', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Netlify-00C7B7?style=for-the-badge&logo=netlify&logoColor=white' },
  { id: 'heroku', name: 'Heroku', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Heroku-430098?style=for-the-badge&logo=heroku&logoColor=white' },
  { id: 'firebase', name: 'Firebase', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Firebase-FFCA28?style=for-the-badge&logo=firebase&logoColor=black' },
  { id: 'digitalocean', name: 'DigitalOcean', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/DigitalOcean-0080FF?style=for-the-badge&logo=digitalocean&logoColor=white' },
  { id: 'cloudflare', name: 'Cloudflare', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Cloudflare-F38020?style=for-the-badge&logo=cloudflare&logoColor=white' },
  { id: 'railway', name: 'Railway', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Railway-0B0D0E?style=for-the-badge&logo=railway&logoColor=white' },
  { id: 'render', name: 'Render', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Render-46E3B7?style=for-the-badge&logo=render&logoColor=white' },
  { id: 'supabase', name: 'Supabase', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/Supabase-3ECF8E?style=for-the-badge&logo=supabase&logoColor=white' },
  { id: 'planetscale', name: 'PlanetScale', category: 'hosting', badgeUrl: 'https://img.shields.io/badge/PlanetScale-000000?style=for-the-badge&logo=planetscale&logoColor=white' },

  // ── SERVERS ──
  { id: 'nginx', name: 'Nginx', category: 'servers', badgeUrl: 'https://img.shields.io/badge/Nginx-009639?style=for-the-badge&logo=nginx&logoColor=white' },
  { id: 'apache', name: 'Apache', category: 'servers', badgeUrl: 'https://img.shields.io/badge/Apache-D22128?style=for-the-badge&logo=apache&logoColor=white' },
  { id: 'caddy', name: 'Caddy', category: 'servers', badgeUrl: 'https://img.shields.io/badge/Caddy-1F88C0?style=for-the-badge&logo=caddy&logoColor=white' },
  { id: 'gunicorn', name: 'Gunicorn', category: 'servers', badgeUrl: 'https://img.shields.io/badge/Gunicorn-499848?style=for-the-badge&logo=gunicorn&logoColor=white' },

  // ── DATABASES & ORM ──
  { id: 'postgresql', name: 'PostgreSQL', category: 'databases', badgeUrl: 'https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white' },
  { id: 'mysql', name: 'MySQL', category: 'databases', badgeUrl: 'https://img.shields.io/badge/MySQL-4479A1?style=for-the-badge&logo=mysql&logoColor=white' },
  { id: 'mongodb', name: 'MongoDB', category: 'databases', badgeUrl: 'https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white' },
  { id: 'redis', name: 'Redis', category: 'databases', badgeUrl: 'https://img.shields.io/badge/Redis-DC382D?style=for-the-badge&logo=redis&logoColor=white' },
  { id: 'sqlite', name: 'SQLite', category: 'databases', badgeUrl: 'https://img.shields.io/badge/SQLite-003B57?style=for-the-badge&logo=sqlite&logoColor=white' },
  { id: 'mariadb', name: 'MariaDB', category: 'databases', badgeUrl: 'https://img.shields.io/badge/MariaDB-003545?style=for-the-badge&logo=mariadb&logoColor=white' },
  { id: 'dynamodb', name: 'DynamoDB', category: 'databases', badgeUrl: 'https://img.shields.io/badge/DynamoDB-4053D6?style=for-the-badge&logo=amazondynamodb&logoColor=white' },
  { id: 'cassandra', name: 'Cassandra', category: 'databases', badgeUrl: 'https://img.shields.io/badge/Cassandra-1287B1?style=for-the-badge&logo=apachecassandra&logoColor=white' },
  { id: 'neo4j', name: 'Neo4j', category: 'databases', badgeUrl: 'https://img.shields.io/badge/Neo4j-008CC1?style=for-the-badge&logo=neo4j&logoColor=white' },
  { id: 'prisma', name: 'Prisma', category: 'databases', badgeUrl: 'https://img.shields.io/badge/Prisma-2D3748?style=for-the-badge&logo=prisma&logoColor=white' },
  { id: 'drizzle', name: 'Drizzle', category: 'databases', badgeUrl: 'https://img.shields.io/badge/Drizzle-C5F74F?style=for-the-badge&logo=drizzle&logoColor=black' },
  { id: 'sequelize', name: 'Sequelize', category: 'databases', badgeUrl: 'https://img.shields.io/badge/Sequelize-52B0E7?style=for-the-badge&logo=sequelize&logoColor=white' },
  { id: 'mongoose', name: 'Mongoose', category: 'databases', badgeUrl: 'https://img.shields.io/badge/Mongoose-880000?style=for-the-badge&logo=mongoose&logoColor=white' },

  // ── DESIGN ──
  { id: 'figma', name: 'Figma', category: 'design', badgeUrl: 'https://img.shields.io/badge/Figma-F24E1E?style=for-the-badge&logo=figma&logoColor=white' },
  { id: 'adobexd', name: 'Adobe XD', category: 'design', badgeUrl: 'https://img.shields.io/badge/Adobe_XD-FF61F6?style=for-the-badge&logo=adobexd&logoColor=white' },
  { id: 'photoshop', name: 'Photoshop', category: 'design', badgeUrl: 'https://img.shields.io/badge/Photoshop-31A8FF?style=for-the-badge&logo=adobephotoshop&logoColor=white' },
  { id: 'illustrator', name: 'Illustrator', category: 'design', badgeUrl: 'https://img.shields.io/badge/Illustrator-FF9A00?style=for-the-badge&logo=adobeillustrator&logoColor=white' },
  { id: 'aftereffects', name: 'After Effects', category: 'design', badgeUrl: 'https://img.shields.io/badge/After_Effects-9999FF?style=for-the-badge&logo=adobeaftereffects&logoColor=white' },
  { id: 'premiere', name: 'Premiere Pro', category: 'design', badgeUrl: 'https://img.shields.io/badge/Premiere_Pro-9999FF?style=for-the-badge&logo=adobepremierepro&logoColor=white' },
  { id: 'canva', name: 'Canva', category: 'design', badgeUrl: 'https://img.shields.io/badge/Canva-00C4CC?style=for-the-badge&logo=canva&logoColor=white' },
  { id: 'sketch', name: 'Sketch', category: 'design', badgeUrl: 'https://img.shields.io/badge/Sketch-F7B500?style=for-the-badge&logo=sketch&logoColor=black' },
  { id: 'blender', name: 'Blender', category: 'design', badgeUrl: 'https://img.shields.io/badge/Blender-F5792A?style=for-the-badge&logo=blender&logoColor=white' },
  { id: 'storybook', name: 'Storybook', category: 'design', badgeUrl: 'https://img.shields.io/badge/Storybook-FF4785?style=for-the-badge&logo=storybook&logoColor=white' },
  { id: 'framer', name: 'Framer', category: 'design', badgeUrl: 'https://img.shields.io/badge/Framer-0055FF?style=for-the-badge&logo=framer&logoColor=white' },

  // ── ML / DL ──
  { id: 'tensorflow', name: 'TensorFlow', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/TensorFlow-FF6F00?style=for-the-badge&logo=tensorflow&logoColor=white' },
  { id: 'pytorch', name: 'PyTorch', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/PyTorch-EE4C2C?style=for-the-badge&logo=pytorch&logoColor=white' },
  { id: 'scikitlearn', name: 'scikit-learn', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/scikit--learn-F7931E?style=for-the-badge&logo=scikit-learn&logoColor=white' },
  { id: 'keras', name: 'Keras', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/Keras-D00000?style=for-the-badge&logo=keras&logoColor=white' },
  { id: 'pandas', name: 'Pandas', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/Pandas-150458?style=for-the-badge&logo=pandas&logoColor=white' },
  { id: 'numpy', name: 'NumPy', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/NumPy-013243?style=for-the-badge&logo=numpy&logoColor=white' },
  { id: 'opencv', name: 'OpenCV', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/OpenCV-5C3EE8?style=for-the-badge&logo=opencv&logoColor=white' },
  { id: 'jupyter', name: 'Jupyter', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/Jupyter-F37626?style=for-the-badge&logo=jupyter&logoColor=white' },
  { id: 'huggingface', name: 'Hugging Face', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/Hugging_Face-FFD21E?style=for-the-badge&logo=huggingface&logoColor=black' },
  { id: 'matplotlib', name: 'Matplotlib', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/Matplotlib-11557C?style=for-the-badge&logo=matplotlib&logoColor=white' },
  { id: 'mlflow', name: 'MLflow', category: 'mldl', badgeUrl: 'https://img.shields.io/badge/MLflow-0194E2?style=for-the-badge&logo=mlflow&logoColor=white' },

  // ── CI/CD & VCS ──
  { id: 'git', name: 'Git', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Git-F05032?style=for-the-badge&logo=git&logoColor=white' },
  { id: 'github', name: 'GitHub', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/GitHub-181717?style=for-the-badge&logo=github&logoColor=white' },
  { id: 'gitlab', name: 'GitLab', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/GitLab-FC6D26?style=for-the-badge&logo=gitlab&logoColor=white' },
  { id: 'bitbucket', name: 'Bitbucket', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Bitbucket-0052CC?style=for-the-badge&logo=bitbucket&logoColor=white' },
  { id: 'githubactions', name: 'GitHub Actions', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white' },
  { id: 'docker', name: 'Docker', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=docker&logoColor=white' },
  { id: 'kubernetes', name: 'Kubernetes', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Kubernetes-326CE5?style=for-the-badge&logo=kubernetes&logoColor=white' },
  { id: 'jenkins', name: 'Jenkins', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Jenkins-D24939?style=for-the-badge&logo=jenkins&logoColor=white' },
  { id: 'circleci', name: 'CircleCI', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/CircleCI-343434?style=for-the-badge&logo=circleci&logoColor=white' },
  { id: 'travisci', name: 'Travis CI', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Travis_CI-3EAAAF?style=for-the-badge&logo=travisci&logoColor=white' },
  { id: 'terraform', name: 'Terraform', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Terraform-7B42BC?style=for-the-badge&logo=terraform&logoColor=white' },
  { id: 'ansible', name: 'Ansible', category: 'cicd', badgeUrl: 'https://img.shields.io/badge/Ansible-EE0000?style=for-the-badge&logo=ansible&logoColor=white' },

  // ── TESTING ──
  { id: 'jest', name: 'Jest', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Jest-C21325?style=for-the-badge&logo=jest&logoColor=white' },
  { id: 'cypress', name: 'Cypress', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Cypress-17202C?style=for-the-badge&logo=cypress&logoColor=white' },
  { id: 'playwright', name: 'Playwright', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Playwright-2EAD33?style=for-the-badge&logo=playwright&logoColor=white' },
  { id: 'vitest', name: 'Vitest', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Vitest-6E9F18?style=for-the-badge&logo=vitest&logoColor=white' },
  { id: 'mocha', name: 'Mocha', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Mocha-8D6748?style=for-the-badge&logo=mocha&logoColor=white' },
  { id: 'selenium', name: 'Selenium', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Selenium-43B02A?style=for-the-badge&logo=selenium&logoColor=white' },
  { id: 'pytest', name: 'Pytest', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Pytest-0A9EDC?style=for-the-badge&logo=pytest&logoColor=white' },
  { id: 'testinglibrary', name: 'Testing Library', category: 'testing', badgeUrl: 'https://img.shields.io/badge/Testing_Library-E33332?style=for-the-badge&logo=testing-library&logoColor=white' },

  // ── OTHER ──
  { id: 'linux', name: 'Linux', category: 'other', badgeUrl: 'https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black' },
  { id: 'ubuntu', name: 'Ubuntu', category: 'other', badgeUrl: 'https://img.shields.io/badge/Ubuntu-E95420?style=for-the-badge&logo=ubuntu&logoColor=white' },
  { id: 'windows', name: 'Windows', category: 'other', badgeUrl: 'https://img.shields.io/badge/Windows-0078D6?style=for-the-badge&logo=windows&logoColor=white' },
  { id: 'macos', name: 'macOS', category: 'other', badgeUrl: 'https://img.shields.io/badge/macOS-000000?style=for-the-badge&logo=apple&logoColor=white' },
  { id: 'neovim', name: 'Neovim', category: 'other', badgeUrl: 'https://img.shields.io/badge/Neovim-57A143?style=for-the-badge&logo=neovim&logoColor=white' },
  { id: 'vscode', name: 'VS Code', category: 'other', badgeUrl: 'https://img.shields.io/badge/VS_Code-007ACC?style=for-the-badge&logo=visual-studio-code&logoColor=white' },
  { id: 'graphql', name: 'GraphQL', category: 'other', badgeUrl: 'https://img.shields.io/badge/GraphQL-E10098?style=for-the-badge&logo=graphql&logoColor=white' },
  { id: 'rabbitmq', name: 'RabbitMQ', category: 'other', badgeUrl: 'https://img.shields.io/badge/RabbitMQ-FF6600?style=for-the-badge&logo=rabbitmq&logoColor=white' },
  { id: 'kafka', name: 'Apache Kafka', category: 'other', badgeUrl: 'https://img.shields.io/badge/Apache_Kafka-231F20?style=for-the-badge&logo=apachekafka&logoColor=white' },
  { id: 'postman', name: 'Postman', category: 'other', badgeUrl: 'https://img.shields.io/badge/Postman-FF6C37?style=for-the-badge&logo=postman&logoColor=white' },
  { id: 'notion', name: 'Notion', category: 'other', badgeUrl: 'https://img.shields.io/badge/Notion-000000?style=for-the-badge&logo=notion&logoColor=white' },
  { id: 'jira', name: 'Jira', category: 'other', badgeUrl: 'https://img.shields.io/badge/Jira-0052CC?style=for-the-badge&logo=jira&logoColor=white' },
  { id: 'raspberrypi', name: 'Raspberry Pi', category: 'other', badgeUrl: 'https://img.shields.io/badge/Raspberry_Pi-A22846?style=for-the-badge&logo=raspberrypi&logoColor=white' },
  { id: 'arduino', name: 'Arduino', category: 'other', badgeUrl: 'https://img.shields.io/badge/Arduino-00979D?style=for-the-badge&logo=arduino&logoColor=white' },
];
